coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: 'reach,diff,flags,tree,footer'
  behavior: default
  require_changes: false

ignore:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/__tests__/**'
  - '**/__mocks__/**'
  - '**/node_modules/**'
  - '**/*.d.ts'
  - '**/test-utils/**'
  - '**/*.config.js'
  - '**/*.config.ts'
